- id: clang-format
  name: clang-format
  description: Format C code using clang-format.
  language: system
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  entry: clang-format -i
  args: ["-style=Google"]
- id: cpplint
  name: cpplint
  description: Check style of C code using cpplint.
  language: python
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  entry: cpplint
  args: ["--verbose=3"]
- id: cppcheck
  name: cppcheck
  description: Check correctness of C code using cppcheck.
  language: system
  files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
  entry: cppcheck --error-exitcode=1
  args: ["--enable=warning"]
- id: flawfinder
  name: flawfinder
  description: a static analysis tool for finding vulnerabilities in C/C++ source code
  language: python
  files: \.(c|cc|cxx|cpp)$
  entry: flawfinder
